### ISSUE TITLE
OpenShift reencrypt route not working (/partition/openshift_route_cluster_default-ca missing)

### ISSUE THREAD

**Issue by rheinzma** [F5Networks/k8s-bigip-ctlr#1288]
#### Description

When creating a route in `cluster` mode with `--manage-routes=true` that is set to `reencrypt`, the server ssl profile `openshift_route_cluster_default-ca` is not created and the vServer can not be created. Also the CIS deletes the profile `openshift_route_cluster_default-ca` if manually created.

#### Kubernetes Version

OpenShift 4.4.3

#### Controller Version

Starting: Version: 1.14.0, BuildInfo: n2285-661543171

#### BIG-IP Version

BIG-IP 13.1.3.3 Build 0.0.6 Point Release 3 

#### Diagnostic Information

Route:

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    # See https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.11/#supported-route-annotations
    virtual-server.f5.com/balance: least-connections-node
    virtual-server.f5.com/secure-serverssl: "true"
    virtual-server.f5.com/health: |
      [{
        "path": "/",
        "interval": 5,
        "timeout": 10,
        "type": "https",
        "send": "GET / HTTP/1.0\r\n",
        "recv": "200|OK"
      }]
  labels:
    app: test-deployment-1
  name: test-deployment-1
  namespace: my-test
spec:
  host: test-deployment-1-my-test.apps.example.ocp.example.com
  port:
    targetPort: 8080-8080
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: test-deployment-1
    weight: 100
  wildcardPolicy: None

```

CIS Deployment: 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      serviceAccountName: k8s-bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--log-level=INFO",
            "--insecure=true",
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=192.168.100.95",
            "--default-ingress-ip=192.168.130.32",
            "--bigip-partition=ocp-diconnected",
            "--namespace-label=ingress.f5",
            "--pool-member-type=cluster",
            "--openshift-sdn-name=/ocp-diconnected/openshift_vxlan",
            "--manage-routes=true",
            "--manage-configmaps=true",
            "--route-vserver-addr=192.168.130.20"
          ]
```

Log message:
```
2020/05/06 23:53:26 [INFO] Text: '{"code":400,"message":"0107134a:3: File object by name (/ocp-diconnected/openshift_route_cluster_default-ca.crt) is missing.","errorStack":[],"apiError":3}'
2020/05/06 23:53:26 [ERROR] [2020-05-06 23:53:26,437 f5_cccl.utils.profile ERROR] Error creating server SSL profile: 400 Unexpected Error: Bad Request for uri: https://192.168.100.95:443/mgmt/tm/ltm/profile/server-ssl/
2020/05/06 23:53:26 [INFO] [2020-05-06 23:53:26,740 f5_cccl.resource.resource INFO] Creating ApiVirtualServer: /ocp-diconnected/https-ose-vserver
2020/05/06 23:53:26 [INFO] Text: '{"code":404,"message":"01020036:3: The requested profile (/ocp-diconnected/default-route-serverssl) was not found.","errorStack":[],"apiError":3}'
2020/05/06 23:53:26 [ERROR] [2020-05-06 23:53:26,788 f5_cccl.resource.resource ERROR] HTTP error(404): CCCL resource(ApiVirtualServer) /ocp-diconnected/https-ose-vserver.
2020/05/06 23:53:26 [ERROR] [2020-05-06 23:53:26,789 f5_cccl.service.manager ERROR] F5CcclResourceNotFoundError - 404 Unexpected Error: Not Found for uri: https://192.168.100.95:443/mgmt/tm/ltm/virtual/
2020/05/06 23:53:26 [ERROR] [2020-05-06 23:53:26,789 f5_cccl.service.manager ERROR] Resource /ocp-diconnected/https-ose-vserver creation error, requeuing task...
2020/05/06 23:53:27 [ERROR] [2020-05-06 23:53:27,144 __main__ ERROR] Error applying config, will try again in 128 seconds
```

**Comment by mdditt2000** [comment]
hello @rheinzma this is resolved using the AS3 API - "--agent=as3"

Please can you move to the AS3 agent and API. Legacy CCCL api doesn't have the latest enhancements needed. Here is guide to help you. https://github.com/mdditt2000/openshift-3-11/blob/master/enviroment/standalone/big-ip-83/QuickStartGuide.md

Please use AS3-17 with CIS 1.14. The link provides guidelines on how to download the AS3 API rpm. 

Also note we are working on implementing TargetPorts and wilcards. Thanks Mark

**Comment by rheinzma** [comment]
Thanks for the hint, I installed AS3 agent, however now I run into problems with route domains. 

I am using route domains for the partitions to allow connecting multiple OCP clusters to a single F5 device in cluster mode (using same podNetwork). With `--agent=as3` it seems that a new partition is created on the F5 device `$OldPartitionName_AS3` and the objects are created here, however the route domain of the new partition is not the same route domain as `$OldPartitionName`, so connectivity is broken. 

Do I need to create the route domains in "Common" then as I have created them within the partitions.?

**Comment by rheinzma** [comment]
Actually I think what I see with the AS3 agent is the same issue as in https://github.com/F5Networks/k8s-bigip-ctlr/issues/1287.

**Comment by mdditt2000** [comment]
Internal PM Jira CONTCNTR-1751. Would add option to the CIS controller that will allow for a route domain example defaultRouteDomain": 10,

Only one route domain will be support per CIS controller.

**Comment by rheinzma** [comment]
I tested with the 1.14 version using `--agent=as3` and it still failes. The reencrypt route is created as normal route.

Now I get the following error with a **reencrypt** route: 

```
2020/05/14 21:55:41 [ERROR] Error parsing ConfigMap rh-test_override-as3-cm
2020/05/14 21:55:41 [WARNING] No profile information supplied for Route 'test-deployment-1'
2020/05/14 21:55:41 [WARNING] Overwriting existing entry for backend {ServiceName:test-deployment-1 ServicePort:8080 Namespace:rh-test}
2020/05/14 21:55:41 [ERROR] Unable to find serverssl for Data Group: ssl_reencrypt_serverssl_dg
```

Note: I used the route domain overwrite thing from https://github.com/F5Networks/k8s-bigip-ctlr/issues/1287 in ConfigMap override-as3-cm

```
            "--override-as3-declaration=rh-test/override-as3-cm",
```

```
shell$ oc get cm override-as3-cm -n rh-test -o yaml
apiVersion: v1
data:
  template: |
    {
        "declaration": {
            "ocp-diconnected_AS3": {
                "defaultRouteDomain": 3
            }
        }
    }
kind: ConfigMap
metadata:
  labels:
    f5type: virtual-server
    overrideAS3: "true"
  name: override-as3-cm
```

**Comment by mdditt2000** [comment]
Jira is closed and resolved. Release is CIS 2.1 shipping next month. Closing Github
