### ISSUE TITLE
f5-bigip-ctlr 2.8.0 occasionally crash with go backtrace

### ISSUE THREAD

**Issue by lenny87** [F5Networks/k8s-bigip-ctlr#2345]
#### Setup Details
 CIS Version : 2.8.0
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.2.1
 AS3 Version: 3.30
 Agent Mode: AS3   
 Orchestration: K8S
 Orchestration Version:1.18.10
 Pool Mode: Cluster     
 Additional Setup details: Ubuntu Linux / Weave net

#### Description  
 f5-bigip-ctlr occasionally crash with go backtrace

#### Diagnostic Information
```
2022/04/06 09:04:36 [INFO] [INIT] Starting: Container Ingress Services - Version: 2.8.0, BuildInfo: azure-2133-2d5eb1b618a8e26381ab81dbacff87286121c73e
2022/04/06 09:04:37 [INFO] ConfigWriter started: 0xc000694240
2022/04/06 09:04:37 [INFO] Started config driver sub-process at pid: 24
2022/04/06 09:04:37 [INFO] [INIT] Creating Agent for as3
2022/04/06 09:04:37 [INFO] [AS3] Initializing AS3 Agent
2022/04/06 09:04:39 [INFO] [CORE] NodePoller (0xc000242090) registering new listener: 0x17b1fa0
2022/04/06 09:04:39 [INFO] [CORE] NodePoller started: (0xc000242090)
2022/04/06 09:04:39 [INFO] [CORE] Watching Ingress resources.
2022/04/06 09:04:39 [INFO] [CORE] Watching ConfigMap resources.
2022/04/06 09:04:39 [INFO] [CORE] Handling ConfigMap resource events.
2022/04/06 09:04:39 [INFO] [CORE] Handling Ingress resource events.
2022/04/06 09:04:39 [INFO] [CORE] Registered BigIP Metrics
2022/04/06 09:04:54 [INFO] [2022-04-06 09:04:54,764 __main__ INFO] entering inotify loop to watch /tmp/k8s-bigip-ctlr.config145023463/config.json
I0406 09:05:46.963279       1 trace.go:205] Trace[1474941318]: "Reflector ListAndWatch" name:github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:936 (06-Apr-2022 09:04:39.570) (total time: 67392ms):
Trace[1474941318]: ---"Objects listed" 67203ms (09:05:00.773)
Trace[1474941318]: [1m7.392962358s] [1m7.392962358s] END
fatal error: concurrent map iteration and map write

goroutine 3917 [running]:
runtime.throw(0x1bb49f3, 0x26)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc01c89bd30 sp=0xc01c89bd00 pc=0x4381f2
runtime.mapiternext(0xc01c89bf60)
	/usr/local/go/src/runtime/map.go:853 +0x554 fp=0xc01c89bdb0 sp=0xc01c89bd30 pc=0x4127b4
github.com/F5Networks/k8s-bigip-ctlr/pkg/teem.(*TeemsData).PostTeemsData(0xc0006b81a0, 0x0)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/teem/teem.go:84 +0x411 fp=0xc01c89bfd0 sp=0xc01c89bdb0 pc=0x74e831
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc01c89bfd8 sp=0xc01c89bfd0 pc=0x46d781
created by github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).deployResource
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/agentRequestHandler.go:32 +0x5e5

```  

Full backtrace in attachment
[f5-bigip-ctrl.log](https://github.com/F5Networks/k8s-bigip-ctlr/files/8425497/f5-bigip-ctrl.log)

**Comment by trinaths** [comment]
@lenny87 - Please configure CIS with `--disable-teems=true` and share your findings.

**Comment by lenny87** [comment]
Ok, I just changed args in deployment
```
    spec:
      containers:
      - args:
        - --credentials-directory
        - /tmp/creds
        - --as3-validation=true
        - --bigip-partition=k8s
        - --node-poll-interval=15
        - --bigip-url=172.16.15.101
        - --default-ingress-ip=CENSORED
        - --insecure=true
        - --log-level=INFO
        - --log-as3-response=true
        - --manage-configmaps=true
        - --manage-ingress=true
        - --manage-routes=false
        - --pool-member-type=cluster
        - --tls-version=1.3
        - --cipher-group=/Common/f5-default
        - --disable-teems=true
        command:
        - /app/bin/k8s-bigip-ctlr
```

Will let you know if the change helped tommorow.

**Comment by lenny87** [comment]
It helped a bit, I have just 1 pod restard after 19hrs (was about ~10) before, but issue still exists.
Latest backtrace attached

[f5-bigip-ctrl.log](https://github.com/F5Networks/k8s-bigip-ctlr/files/8473659/f5-bigip-ctrl.log)

**Comment by arzzon** [comment]
Issue has been resolved with CIS v2.9.0

**Comment by ttaylor249** [comment]
We're seeing this same error message ("fatal error: concurrent map iteration and map write") even with CIS v2.9.0.  I've attached the pod log.

Increasing the verify-interval from the default of 30 seconds to 120 seconds seems to have helped somewhat.  But we're still seeing the CIS pod restart 3-4 times per hour.

[cis-ctlr-logs-trim-v2.9.0.log](https://github.com/F5Networks/k8s-bigip-ctlr/files/9066660/cis-ctlr-logs-trim-v2.9.0.log)

**Comment by cript2000** [comment]
Still seeing the issue on 2.9.1

**Comment by mdditt2000** [comment]
@cript2000 @ttaylor249 @lenny87 Please note

This issue is fixed with https://github.com/F5Networks/k8s-bigip-ctlr/pull/2512 and
https://github.com/F5Networks/k8s-bigip-ctlr/pull/2500

Please use build **cisbot/k8s-bigip-ctlr:teemCrashFix** until 2.10 release. CIS 2.10 is scheduled for release around 06/Sep/22

**Comment by mdditt2000** [comment]
@vklohiya identify as not a teem crash. So this needs to be resolved in CIS 2.10 SP3.
