### ISSUE TITLE
Weird behavior in case of regeneration operation error

### ISSUE THREAD

**Issue by bonky42** [F5Networks/k8s-bigip-ctlr#281]
Hi,
We've encountered a strange behavior in version 1.1
when we entered a virtual server configuration by a configmap like this one, there is no existing one.

```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jenkins
  namespace: infsy
  labels: 
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.3.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 8080,
          "serviceName": "jenkins-ui",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET",
            "timeout": 86400
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 80,
            "bindAddr": "10.181.34.1"
          },
          "partition": "kubernetes",
          "balance": "round-robin",
          "mode": "http"
        }
      }
    }
```

I've got this error:
```
2017/08/11 15:19:16 [ERROR] [2017-08-11 15:19:16,203 controller ERROR] HTTP Error: 400 Unexpected Error: Bad Request for uri: https://*.*.*.*:443/mgmt/tm/ltm/virtual-address/
2017/08/11 15:19:16 [INFO] Text: u'{"code":400,"message":"0107176c:3: Invalid Virtual Address, the IP address 10.181.34.1%4 already exists.","errorStack":[]}'
2017/08/11 15:19:16 [WARNING] [2017-08-11 15:19:16,203 __main__ WARNING] regenerate operation failed, restarting
```

Another thing is if I try to add another configmap with an iapp it will not do anything while I still have an error, as soon as I remove the configmap with an error the one with the iapp works.

**Comment by sjberman** [comment]
Do you have a virtual server anywhere else on the BIG-IP with IP address 10.181.34.1?

**Comment by bonky42** [comment]
no, it's a brand new partition and the range of ip is dedicated.

**Comment by sjberman** [comment]
Do you have a virtual server in a different partition, in the default route domain? (for example: 0.0.0.0:any or 0.0.0.0:0)

**Comment by bonky42** [comment]
not that I know, I will check on wednesday.

**Comment by bonky42** [comment]
I have checked and I've different virtual server in others partition, but
each has is own address range, none like your example.

Bernard CHESNOY

https://twitter.com/Bonky42
http://www.pavillon-noir.eu

**Comment by sjberman** [comment]
Ok, interesting. Here is a reference of what I was looking at: https://support.f5.com/csp/article/K91528447. My first impressions are that this is still a BIG-IP issue, but I'll try to dig a bit deeper.

**Comment by sjberman** [comment]
Is the route domain number appended to the IP address what it should be? `10.181.34.1%4`

**Comment by bonky42** [comment]
Yes it's the correct one.
Just one thing, the virtual server is created on the F5, and this error occurs after.
The biggest problem for me is that it will not allow to create others iapps while there is the error.

**Comment by sjberman** [comment]
Ok so I think the error message you are seeing is BIG-IP related, not controller related. However, I will look into the issue of not being able to create iapps after the error occurs, because that likely is a controller problem.

**Comment by bonky42** [comment]
Hello again, I found something interesting in the log on the F5, it seems the controller is calling this address:
https://*******/mgmt/tm/ltm/virtual-address/~kubernetes~10.181.34.1

But the F5 will say it does not exist, if I add the partition number after this url like this:
https://*******/mgmt/tm/ltm/virtual-address/~kubernetes~10.181.34.1%2542 (42 is the number of the partition and %25 the code for the "%" character)
It will work.
The conclusion for this is it seems the controller do not call the correct uri, so form him the virtualserver does not exist and will try to create it again and get the already exist error.
Maybe it can help on the matter.

**Comment by sjberman** [comment]
One other thing to check is if there is a Virtual Address hanging around in the partition. Sometimes even when the Virtual Server is deleted, the address may hang around, causing conflicts.

On the point about not being able to create iapps after a bad config is processed, this is an issue that we have fixed in our next release, so it is coming.

**Comment by bonky42** [comment]
I already try this:
* cleaning all the conf on the interface
* check that the file bigip.conf is clean
* force the load of the file conf with tmsh
* add config map
* check it is created in f5
* force the sync to the file with tmsh
And I still have the error
the controller is still asking with an uri where there isn't the partition
number

another thing for you I've got the version 11.6.1 of f5

**Comment by sjberman** [comment]
Alright I was finally able to reproduce this! Thank you for the information you provided, it definitely helped narrow this down.

Our next step is discussing how best to fix this bug, while still being able to properly support route domains going forward.

**Comment by bonky42** [comment]
Great news, thanks for your responsivness

**Comment by sjberman** [comment]
@bonky42 Just an update for you; we are currently planning on how to correctly support route domains going forward. We will be scheduling work on this fix/feature and it should be included in an upcoming release.

**Comment by bonky42** [comment]
thanks for the update

**Comment by sjberman** [comment]
This has been fixed in the latest (1.3.0) release.
