### ISSUE TITLE
Ingress Resource - Error updating https_redirect_dg

### ISSUE THREAD

**Issue by codertao** [F5Networks/k8s-bigip-ctlr#975]
#### Description
The k8s controller is generating error logs and not adding new hostnames to the http to https redirect datagroup.

If I go through and manually delete the group, it'll create/sync the datagroup correctly, but be back to unable to update it the next time it needs to change.

#### Kubernetes Version
EKS 1.11

#### Controller Version
1.9.1

#### BIG-IP Version
AWS Market Place BIGIP VE
BIG-IP 14.0.0.1 Build 0.0.2 Point Release 1 

#### Diagnostic Information

```
> 2019/07/25 21:57:06 [INFO] [2019-07-25 21:57:06,546 f5_cccl.resource.resource INFO] Updating ApiInternalDataGroup: /staging/https_redirect_dg
> 2019/07/25 21:57:06 [ERROR] [2019-07-25 21:57:06,639 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiInternalDataGroup) /cwf-staging/https_redirect_dg.
> 2019/07/25 21:57:06 [ERROR] [2019-07-25 21:57:06,639 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.0.0.5:443/mgmt/tm/ltm/data-group/internal/~staging~https_redirect_dg/
> 2019/07/25 21:57:06 [INFO] Text: u'{"code":400,"message":"0107074b:3: Unable to change data group (/staging/https_redirect_dg) type. Must remove existing entries first.","errorStack":[],"apiError":3}'
> 2019/07/25 21:57:06 [ERROR] [2019-07-25 21:57:06,639 f5_cccl.service.manager ERROR] Resource /staging/https_redirect_dg update error, requeuing task...
> 2019/07/25 21:57:07 [ERROR] [2019-07-25 21:57:07,432 __main__ ERROR] Error applying config, will try again in 128 seconds
```

Example ingress:

```yaml
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   annotations:
>     virtual-server.f5.com/ip: controller-default
>   name: app
> spec:
>   rules:
>   - host: normal-host-name.com
>     http:
>       paths:
>       - backend:
>           serviceName: app
>           servicePort: 80
>   tls:
>   - hosts:
>     - normal-host-name.com
>     secretName: the-secret-name
```

**Comment by trinaths** [comment]
@codertao : Can you look into the error for the above diagnostic info,

Unable to change data group (/staging/https_redirect_dg) type. Must remove existing entries first.

I think updating your data group can resolve this.

**Comment by codertao** [comment]
Going through and deleting the data group does "fix it", until another new
domain needs to be added.

If I recall correctly, manually clearing out the entries doesn't work, as
it's trying to delete the data group, but the group is still in use by the
redirect irule.

**Comment by mdditt2000** [comment]
This will be address in CIS 1.12 with the rework of K8S ingress to AS3

**Comment by Timoses** [comment]
Same here.
Controller version: `1.10.0`
K8s cluster: Bare metal

**Comment by Timoses** [comment]
I have the following:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    virtual-server.f5.com/ip: controller-default
spec:
  tls:
  - hosts:
    - cafe.kubernetes.hss.int
    secretName: cafe-secret
  rules:
  - host: cafe.kubernetes.hss.int
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```

It will automatically throw the error after populating `https_redirect_dg` with `/tea` because it tries to add `/coffee`. When I delete `https_redirect_dg` again, next time it added `/coffee` but will soon try to add `/tea` resulting in the same error again..

**Comment by codertao** [comment]
For the record, this is related to https://github.com/F5Networks/f5-common-python/issues/1535 ; a problem in the f5-common-python module and BigIP 14.x

**Comment by Timoses** [comment]
> For the record, this is related to [F5Networks/f5-common-python#1535](https://github.com/F5Networks/f5-common-python/issues/1535) ; a problem in the f5-common-python module and BigIP 14.x

As a note: We run `BIG-IP 14.0.0.1 Build 0.0.2 Point Release 1` as well

**Comment by mdditt2000** [comment]
Created CONTCNTR-1159 for PM tracking

**Comment by veeramalla-f5** [comment]
This is fixed as part of pull request https://github.com/F5Networks/k8s-bigip-ctlr/pull/1126

This is be part of release 1.13

**Comment by Timoses** [comment]
This still happens in 1.13:
```
> ks get deployments.apps f5-bigip-ctlr -o yaml | grep "image:"                                                                                                                                                             bio-dev 0 0jobs
        image: f5networks/k8s-bigip-ctlr:1.13.0
```
```
2020/03/04 10:18:10 [INFO] [2020-03-04 10:18:10,347 f5_cccl.resource.resource INFO] Updating ApiInternalDataGroup: /mypartition/https_redirect_dg
2020/03/04 10:18:10 [ERROR] [2020-03-04 10:18:10,411 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiInternalDataGroup) /mypartition/https_redirect_dg.
2020/03/04 10:18:10 [ERROR] [2020-03-04 10:18:10,411 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://172.28.1.34:443/mgmt/tm/ltm/data-group/internal/~mypartition~https_redirect_dg/
2020/03/04 10:18:10 [INFO] Text: u'{"code":400,"message":"0107074b:3: Unable to change data group (/mypartition/https_redirect_dg) type.  Must remove existing entries first.","errorStack":[],"apiError":3}'
2020/03/04 10:18:10 [ERROR] [2020-03-04 10:18:10,411 f5_cccl.service.manager ERROR] Resource /mypartition/https_redirect_dg update error, requeuing task...
2020/03/04 10:18:10 [ERROR] [2020-03-04 10:18:10,637 __main__ ERROR] Error applying config, will try again in 64 seconds
```

**Comment by veeramalla-f5** [comment]
Are u running the controller in CCCL mode or AS3 ?

**Comment by Timoses** [comment]
> Are u running the controller in CCCL mode or AS3 ?

Using default Ingress resource. 

The following example appears to trigger the error (from https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example):

```
k apply -f https://gist.githubusercontent.com/Timoses/18a065a6107df0716035935392587cea/raw/be4c35211221358f0bfa6163e4ff8b2f2fa11acf/cafe_1.yaml
```

then
```
k apply -f https://gist.githubusercontent.com/Timoses/18a065a6107df0716035935392587cea/raw/be4c35211221358f0bfa6163e4ff8b2f2fa11acf/cafe_2.yaml
```

**Comment by Timoses** [comment]
Still occurs in v0.14.0

As soon as two Ingress resources are used with TLS the error is thrown:
```
2020/04/30 15:34:18 [INFO] [2020-04-30 15:34:18,650 f5_cccl.resource.resource INFO] Updating ApiInternalDataGroup: /rancher-dev-1.hss.int/https_redirect_dg
2020/04/30 15:34:18 [ERROR] [2020-04-30 15:34:18,762 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiInternalDataGroup) /rancher-dev-1.hss.int/https_redirect_dg.
2020/04/30 15:34:18 [INFO] Text: '{"code":400,"message":"0107074b:3: Unable to change data group (/rancher-dev-1.hss.int/https_redirect_dg) type.  Must remove existing entries first.","errorStack":[],"apiError":3}'
2020/04/30 15:34:18 [ERROR] [2020-04-30 15:34:18,763 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://172.28.1.34:443/mgmt/tm/ltm/data-group/internal/~rancher-dev-1.hss.int~https_redirect_dg/
2020/04/30 15:34:18 [ERROR] [2020-04-30 15:34:18,763 f5_cccl.service.manager ERROR] Resource /rancher-dev-1.hss.int/https_redirect_dg update error, requeuing task...
2020/04/30 15:34:19 [ERROR] [2020-04-30 15:34:19,223 __main__ ERROR] Error applying config, will try again in 128 seconds
```

```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      virtual-server.f5.com/ip: controller-default
    name: argocd-server-http-ingress
    namespace: argocd
  spec:
    rules:
    - host: argocd.test.int
      http:
        paths:
        - backend:
            serviceName: argocd-server
            servicePort: 80
    tls:
    - hosts:
      - argocd.test.int
      secretName: argocd-secret
```

```
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      virtual-server.f5.com/ip: controller-default
    name: testapp
    namespace: testns
  spec:
    rules:
    - host: testapp.test.int
      http:
        paths:
        - backend:
            serviceName: rancher
            servicePort: 80
    tls:
    - hosts:
      - rancher.test.int
      secretName: tls-rancher-hss
```

When will this be fixed?
